
import Head from 'next/head'
import Navbar from '../components/navbar/navbar'
import '../styles/globals.css';

function MyApp({Component, pageProps}) {
  return (
    <div>
      <Head>
        <title>Tectony Create next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous" />
      </Head>

      <Navbar />

      <Component {...pageProps} />
    </div>
  );
}

export default MyApp;
